### ISSUE TITLE
Blacked out Information

### ISSUE THREAD

**Issue by ogradyng** [GoogleCloudPlatform/wsi-to-dicom-converter#32] opened 2020-01-07 19:14 UTC
Hi all-
Thanks for this converter.  I am using this tool in conjunction with QuPath m2 and Google Cloud Platform's datastores.  I've noticed some of my .SVS images when converting to dicom format have blacked out squares.  The images look complete when viewing as .svs, but then are missing information post conversion.  I've converted both through command line, and also loading into qupath and synchronizing to google cloud platform (which I believe uses this tool in the background as well).  I was wondering if you had any insight on this or any work arounds?

wsi converter v1.0.2
Qupath -0.2.0-m2
qupath-chcapi-extension v2.0.2
mac 10.13.6

Thanks!
Nick

**Comment by pavertomato** [comment] 2020-01-08 01:01
>which I believe uses this tool in the background as well

yes, you may find binary inside of jar file
> but then are missing information post conversion. 

Unfortunately this is unresolved bug in dependency https://github.com/openslide/openslide/issues/268, Pixman issue described in comments seems to be linux-specific 

@dzelemba we may implement workaround with offset of 1px for macos, it seems to be hiding bug for most cases

**Comment by dzelemba** [comment] 2020-01-08 14:35
What would the workaround be on our side? Could we contribute a fix to OpenSlide directly?

**Comment by pavertomato** [comment] 2020-01-09 04:24
> What would the workaround be on our side? 

we will request pixels starting from point (1,1) instead of (0,0), it will cut off one line and one column of pixels

>  Could we contribute a fix to OpenSlide directly?

to do that we need to find root cause of the problem, but as i remember we don't want to spend resources for that?

**Comment by dzelemba** [comment] 2020-01-09 13:30
> > What would the workaround be on our side?
> 
> we will request pixels starting from point (1,1) instead of (0,0), it will cut off one line and one column of pixels
@ogradyng : would losing the first row and column of Pixels be an issue for you?
> 
> > Could we contribute a fix to OpenSlide directly?
> 
> to do that we need to find root cause of the problem, but as i remember we don't want to spend resources for that?
Given that we're now hitting this issue, I think it would be worth spending some time to try and figure out the root cause.

**Comment by ogradyng** [comment] 2020-01-09 20:05
>@ogradyng : would losing the first row and column of Pixels be an issue for you?> 
@dzelemba 
Thank you all for the responses and looking at this.  Losing just the first row/column of pixels would be very preferable to the otherwise blacked out squares on the images.  There typically isn't a great deal of image data on the very edges of the images from my experience.

**Comment by dzelemba** [comment] 2020-01-09 22:37
Ok thanks for the feedback.

@pavertomato : let's implement the dropping of the first row/column (behind a command line flag) for now as a workaround and then work on hunting down the root cause here.

**Comment by pavertomato** [comment] 2020-01-10 09:32
> @pavertomato : let's implement the dropping of the first row/column (behind a command line flag) for now as a workaround and then work on hunting down the root cause here.

ok, i'll add it to my backlog, but i guess it will go the end of the queue, or we need to reprioritize tasks as i back from vacation(13th of jan)

**Comment by dzelemba** [comment] 2020-01-17 22:00
@ogradyng : we've just released a new version (https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/releases/tag/v1.0.3) of the tool with this workaround implemented, let us know if it works for you!

**Comment by NickOGrady** [comment] 2020-01-29 00:34
@dzelemba I might need a larger sample size, but actually the v1.0.3 seemed to add another row and column of the black boxes. With both versions though, I am able to still zoom in and see the biopsy clearly (black boxes disappear), so it still is functioning.

**Comment by pavertomato** [comment] 2020-01-29 00:42
> @dzelemba I might need a larger sample size, but actually the v1.0.3 seemed to add another row and column of the black boxes. With both versions though, I am able to still zoom in and see the biopsy clearly (black boxes disappear), so it still is functioning.

have you used new parameter? https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter#dropfirstrowandcolumn if so, is it possible for you to share your example file?
please note - new version of wsi2dcm not yet included in qupath, so dcm files have to be generated by command line tool

**Comment by NickOGrady** [comment] 2020-01-29 00:51
> > @dzelemba I might need a larger sample size, but actually the v1.0.3 seemed to add another row and column of the black boxes. With both versions though, I am able to still zoom in and see the biopsy clearly (black boxes disappear), so it still is functioning.
> 
> have you used new parameter? https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter#dropfirstrowandcolumn 


Ah, sorry! Missed this part.  I just tried it on a few images and it's working great.  Thanks!

**Comment by dzelemba** [comment] 2020-01-29 14:37
Ok great, glad to hear this is working for you! I'll close this issue now and I've filled https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/issues/36 to track the follow up task of fixing this properly.

**Closed by dzelemba** 2020-01-29 14:37 UTC
